[workspace]
members = ["crates/*"]
default-members = ["crates/tui"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
anyhow = "1.0.86"
rand = "0.8.5"
ratatui = "0.27.0"

lib = { package = "snaks-lib", path = "crates/lib" }
