[package]
name = "snaks-tui"
version.workspace = true
edition.workspace = true

[[bin]]
name = "snaks"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
ratatui.workspace = true

lib.workspace = true
